[package]
name = "bankink_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros"] }
banking_demo_web = {path = "src/web"}
